name: cross_connectivity
version: 2.0.1
homepage: https://github.com/marchdev-tk/cross_connectivity
description: A Flutter plugin for handling Connectivity and REAL Connection state in the mobile, web and desktop platforms. Supports iOS, Android, Web, Windows, Linux and macOS.

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.3.0-nullsafety.6
  http: ^0.13.0-nullsafety.0
  rxdart: ^0.26.0-nullsafety.1
  connectivity: ^3.0.0-nullsafety.3
  connectivity_macos: ^0.2.0-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety.3

flutter:
